# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a074483057c730c534b85de0f721635dc0db0c5a641ab5545f0a854a531ef17a9cb11ffad78b8a259381990d8ec8ea924fab96a2b8b639d300fd4672516600b

passenger_set_cgi_param SECRET_KEY_BASE "0a074483057c730c534b85de0f721635dc0db0c5a641ab5545f0a854a531ef17a9cb11ffad78b8a259381990d8ec8ea924fab96a2b8b639d300fd4672516600b"

test:
  secret_key_base: 97001dc6885fb31cfb798ee469740c2746559d020be282119c852cb6c93a331ebea77fffeb89492febc773617e3c3e5143be642213f8554d39a8b9dbe188f321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
